# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverlessdemo

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: ${opt:stage, 'development'}

resources:
  - ${file(serverless/cloudformation/lambdaRole.yml)}
  - ${file(serverless/cloudformation/gatewayresponse.yml)}

functions:
  - ${file(serverless/functions/getHistory.yml)}
  - ${file(serverless/functions/submitHistory.yml)}
custom:
  app: serverlessworkshop
  envVars: ${file(serverless/stagevars/${self:provider.stage}.yml)}

package:
  individually: true